import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :zaimu_tomo, ZaimuTomoWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# Force using SSL in production when the image is compiled with FORCE_SSL=true.
# This deployment defaults to HTTP behind the WireGuard-only Kamal Proxy.
# Note `:force_ssl` is required to be set at compile-time.
if System.get_env("FORCE_SSL") in ~w(true 1) do
  config :zaimu_tomo, ZaimuTomoWeb.Endpoint,
    force_ssl: [rewrite_on: [:x_forwarded_proto]],
    exclude: [
      paths: ["/health", "/up"],
      hosts: ["localhost", "127.0.0.1"]
    ]
end

# Configure Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
